CREATE SCHEMA IF NOT EXISTS ot_nanjing;

CREATE TABLE IF NOT EXISTS ot_nanjing.accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL,
  username TEXT NOT NULL,
  password TEXT NOT NULL,
  display_name TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE (role, username)
);

CREATE TABLE IF NOT EXISTS ot_nanjing.items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  module_key TEXT NOT NULL,
  title TEXT NOT NULL,
  subtitle TEXT,
  status TEXT,
  owner TEXT,
  amount NUMERIC DEFAULT 0,
  description TEXT,
  extra JSONB DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

INSERT INTO ot_nanjing.accounts (id, role, username, password, display_name) VALUES
  (1, 'admin', 'admin', 'admin', '平台管理员'),
  (2, 'user', '账号1', '123456', '旅游用户'),
  (3, 'staff', '景区01', '123456', '景区运营')
ON CONFLICT (role, username) DO UPDATE SET
  password = EXCLUDED.password,
  display_name = EXCLUDED.display_name;

INSERT INTO ot_nanjing.items (id, module_key, title, subtitle, status, owner, amount, description, extra) VALUES
  (1, 'attraction', '景点管理演示记录1', '景点介绍、开放时间、门票和推荐信息', '进行中', '平台管理员', 10, '南京旅游服务平台的景点管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (2, 'attraction', '景点管理演示记录2', '景点介绍、开放时间、门票和推荐信息', '待处理', '旅游用户', 20, '南京旅游服务平台的景点管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (3, 'attraction', '景点管理演示记录3', '景点介绍、开放时间、门票和推荐信息', '已完成', '景区运营', 30, '南京旅游服务平台的景点管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (4, 'hotel', '酒店管理演示记录1', '酒店房型、价格、位置和预订状态', '进行中', '平台管理员', 10, '南京旅游服务平台的酒店管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (5, 'hotel', '酒店管理演示记录2', '酒店房型、价格、位置和预订状态', '待处理', '旅游用户', 20, '南京旅游服务平台的酒店管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (6, 'hotel', '酒店管理演示记录3', '酒店房型、价格、位置和预订状态', '已完成', '景区运营', 30, '南京旅游服务平台的酒店管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (7, 'restaurant', '餐厅管理演示记录1', '特色餐饮、地址、评分和营业状态', '进行中', '平台管理员', 10, '南京旅游服务平台的餐厅管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (8, 'restaurant', '餐厅管理演示记录2', '特色餐饮、地址、评分和营业状态', '待处理', '旅游用户', 20, '南京旅游服务平台的餐厅管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (9, 'restaurant', '餐厅管理演示记录3', '特色餐饮、地址、评分和营业状态', '已完成', '景区运营', 30, '南京旅游服务平台的餐厅管理模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (10, 'route', '旅游路线演示记录1', '行程路线、交通方式和时间安排', '进行中', '平台管理员', 10, '南京旅游服务平台的旅游路线模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (11, 'route', '旅游路线演示记录2', '行程路线、交通方式和时间安排', '待处理', '旅游用户', 20, '南京旅游服务平台的旅游路线模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (12, 'route', '旅游路线演示记录3', '行程路线、交通方式和时间安排', '已完成', '景区运营', 30, '南京旅游服务平台的旅游路线模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (13, 'diary', '旅行游记演示记录1', '用户游记、攻略、图片和互动数据', '进行中', '平台管理员', 10, '南京旅游服务平台的旅行游记模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (14, 'diary', '旅行游记演示记录2', '用户游记、攻略、图片和互动数据', '待处理', '旅游用户', 20, '南京旅游服务平台的旅行游记模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (15, 'diary', '旅行游记演示记录3', '用户游记、攻略、图片和互动数据', '已完成', '景区运营', 30, '南京旅游服务平台的旅行游记模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (16, 'booking', '旅游预订演示记录1', '景点、酒店和餐饮预订记录', '进行中', '平台管理员', 10, '南京旅游服务平台的旅游预订模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (17, 'booking', '旅游预订演示记录2', '景点、酒店和餐饮预订记录', '待处理', '旅游用户', 20, '南京旅游服务平台的旅游预订模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb),
  (18, 'booking', '旅游预订演示记录3', '景点、酒店和餐饮预订记录', '已完成', '景区运营', 30, '南京旅游服务平台的旅游预订模块演示数据，用于验证列表、搜索、新增、编辑和删除流程。', '{}'::jsonb)
ON CONFLICT (id) DO UPDATE SET
  module_key = EXCLUDED.module_key,
  title = EXCLUDED.title,
  subtitle = EXCLUDED.subtitle,
  status = EXCLUDED.status,
  owner = EXCLUDED.owner,
  amount = EXCLUDED.amount,
  description = EXCLUDED.description,
  extra = EXCLUDED.extra,
  updated_at = now();

SELECT setval(pg_get_serial_sequence('ot_nanjing.accounts', 'id'), COALESCE((SELECT MAX(id) FROM ot_nanjing.accounts), 1), true);
SELECT setval(pg_get_serial_sequence('ot_nanjing.items', 'id'), COALESCE((SELECT MAX(id) FROM ot_nanjing.items), 1), true);

CREATE OR REPLACE FUNCTION public.ot_nanjing_demo_rest(
  p_table_name TEXT,
  p_method TEXT DEFAULT 'GET',
  p_query JSONB DEFAULT '{}'::jsonb,
  p_payload JSONB DEFAULT '{}'::jsonb
) RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_schema CONSTANT TEXT := 'ot_nanjing';
  v_table TEXT;
  v_sql TEXT;
  v_rows JSONB := '[]'::jsonb;
  v_key TEXT;
  v_value TEXT;
  v_where TEXT := '';
  v_order TEXT := '';
  v_limit TEXT := '';
  v_set TEXT := '';
  v_columns TEXT := '';
  v_values TEXT := '';
BEGIN
  IF p_table_name NOT IN ('accounts', 'items') THEN
    RAISE EXCEPTION 'table is not allowed: %', p_table_name;
  END IF;

  v_table := format('%I.%I', v_schema, p_table_name);

  FOR v_key, v_value IN SELECT key, value #>> '{}' FROM jsonb_each(p_query)
  LOOP
    IF v_key = 'select' THEN
      CONTINUE;
    ELSIF v_key = 'order' THEN
      v_order := ' ORDER BY ' || quote_ident(split_part(v_value, '.', 1)) ||
        CASE WHEN lower(split_part(v_value, '.', 2)) = 'desc' THEN ' DESC' ELSE ' ASC' END;
    ELSIF v_key = 'limit' THEN
      v_limit := ' LIMIT ' || LEAST(GREATEST(v_value::int, 1), 200);
    ELSIF v_value LIKE 'eq.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' = ' || quote_literal(substring(v_value FROM 4));
    ELSIF v_value LIKE 'ilike.%' THEN
      v_where := v_where || CASE WHEN v_where = '' THEN ' WHERE ' ELSE ' AND ' END ||
        quote_ident(v_key) || ' ILIKE ' || quote_literal(substring(v_value FROM 7));
    END IF;
  END LOOP;

  IF upper(p_method) = 'GET' THEN
    v_sql := 'SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM (SELECT * FROM ' || v_table || v_where || v_order || v_limit || ') t';
    EXECUTE v_sql INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'POST' THEN
    SELECT string_agg(quote_ident(key), ', '), string_agg(quote_literal(value #>> '{}'), ', ')
      INTO v_columns, v_values
    FROM jsonb_each(p_payload)
    WHERE key <> 'id';
    IF v_columns IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'INSERT INTO ' || v_table || ' (' || v_columns || ') VALUES (' || v_values || ') RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'PATCH' THEN
    SELECT string_agg(quote_ident(key) || ' = ' || quote_literal(value #>> '{}'), ', ')
      INTO v_set
    FROM jsonb_each(p_payload)
    WHERE key <> 'id' AND key <> 'created_at';
    IF v_set IS NULL THEN
      RAISE EXCEPTION 'empty payload';
    END IF;
    v_sql := 'UPDATE ' || v_table || ' SET ' || v_set || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  ELSIF upper(p_method) = 'DELETE' THEN
    v_sql := 'DELETE FROM ' || v_table || v_where || ' RETURNING *';
    EXECUTE 'WITH changed AS (' || v_sql || ') SELECT COALESCE(jsonb_agg(to_jsonb(t)), ''[]''::jsonb) FROM changed t' INTO v_rows;
    RETURN v_rows;
  END IF;

  RAISE EXCEPTION 'method is not allowed: %', p_method;
END;
$$;

GRANT EXECUTE ON FUNCTION public.ot_nanjing_demo_rest(TEXT, TEXT, JSONB, JSONB) TO anon, authenticated, service_role;
